[package]
name = "anon-msg"
version = "1.0.0"
description = "AnonMsg - Anonymous & Transparent Social Messaging Platform"
license = "MIT"
entrypoint = "web"

[dependencies]
"wasmer/python" = "^3.12"

[fs]
"/dist" = "dist"
"/main.py" = "main.py"

[[command]]
name = "web"
module = "wasmer/python:python"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
atom = "wasmer/python:python"
main-args = ["main.py"]
env = ["PYTHONUNBUFFERED=1", "PORT=8000", "HOST=0.0.0.0"]
